# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kl < Formula
  desc "A small command-line task manager"
  homepage "https://github.com/semos1204/komlist"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/semos1204/komlist/releases/download/v0.1.3/kl_0.1.3_darwin_amd64.tar.gz"
      sha256 "219a791b45a8e5103326854057768a09bf853c42b7edb2cceaad7cbb86e7dd71"

      define_method(:install) do
        bin.install "kl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/semos1204/komlist/releases/download/v0.1.3/kl_0.1.3_darwin_arm64.tar.gz"
      sha256 "8d7c280cea542196815908086a3acb2f5cb2c4a4fd18d1d0f731e8fec84d05d0"

      define_method(:install) do
        bin.install "kl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/semos1204/komlist/releases/download/v0.1.3/kl_0.1.3_linux_amd64.tar.gz"
      sha256 "0dc538adaac1d0bd18bcbb54759112ca1362ddb5d6575dd0e3d38fb13b8322af"
      define_method(:install) do
        bin.install "kl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/semos1204/komlist/releases/download/v0.1.3/kl_0.1.3_linux_arm64.tar.gz"
      sha256 "a5a67e9ed58b2c60ef252c6e17a6f0aead5a8700f2deafbc94adb18a9a4fa9b6"
      define_method(:install) do
        bin.install "kl"
      end
    end
  end

  test do
    system "#{bin}/kl", "--version"
  end
end
